"""add-vote

Revision ID: a62dfe952f59
Revises: 5abaa9eeade7
Create Date: 2023-07-04 11:37:07.668159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62dfe952f59'
down_revision = '5abaa9eeade7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
